#!/bin/sh

OPTS="-XX:+UnlockExperimentalVMOptions -XX:+UseG1GC"
#DEBUG_OPTS="-XX:+PrintCompilation"
JARS=$(find lib -name *.jar | tr "\n" ":")

java $OPTS $DEBUG_OPTS -cp build/main:build/test:$JARS fixengine.performance.PerformanceTest
