#!/bin/sh

OPTS="-XX:+UnlockExperimentalVMOptions -XX:+UseG1GC"
#DEBUG_OPTS="-XX:+PrintCompilation"

java $OPTS $DEBUG_OPTS -cp build/main:build/test:lib/silvertip-0.1.1.jar:lib/joda-time-1.5.2.jar fixengine.performance.PerformanceTest
